DROP TABLE actor;
DROP TABLE film_actor;
DROP TABLE category;
DROP TABLE language;
DROP TABLE film;
DROP TABLE inventroy;
DROP TABLE rental;
DROP TABLE payment;
DROP TABLE customer;
DROP TABLE address;
CREATE TABLE actor (actor_id integer,first_name text,last_name text);
CREATE TABLE address (address_id integer,address text,district text,city text,postal_code text,phone text);
CREATE TABLE category (film_id integer,category text);
CREATE TABLE customer (customer_id integer,first_name text,last_name text,email text,address_id integer,active boolean);
CREATE TABLE film (film_id integer,title text,description text,release_year integer,language_id integer,rental_duration integer,rental_rate double precision,length integer,replacement_cost double precision,rating text,special_features text);
CREATE TABLE film_actor (actor_id integer,film_id integer);
CREATE TABLE inventory (inventory_id integer,film_id integer);
CREATE TABLE language (language_id integer,name text,last_update timestamp with time zone);
CREATE TABLE payment (payment_id integer,customer_id integer,rental_id integer,amount double precision,payment_date timestamp with time zone);
CREATE TABLE rental (rental_id integer,rental_date timestamp with time zone,inventory_id integer,customer_id integer,return_date timestamp with time zone);