# -*- coding: utf-8 -*-
"""Practical (repeat).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14gi6q5zSZT_KwQMzux9p3J4dtewHAijX
"""

print("This is the first sentence. \n This is another sentence.")

name = input("Enter your name: ")

age = input("Enter your age: ")

age = int(age)

current_year = 2023

year_turn_100 = current_year + (100 - age)

year_turn_100 = str(year_turn_100)

print("Hey " + name + " you will be 100 years old in " + year_turn_100)

print(f"Hey {name} you will be 100 years old in {year_turn_100}")

sentence = "Sunny days are the best. I am always in the best mood when it is sunny. If you ask me what the best weather is, I will say SUNNY!"

new_sentence = sentence.lower()

count_sunny = new_sentence.count("sunny")

print(count_sunny)

word = "Hello"
len_word = len(word)

print(len_word)

# Implicit casting

x = 10
y = 5.0

sum = x + y
print(sum)

# Explicit casting

num = "42"

num_int = int(num)

product = 5*2
div = 20/2
mod = 9%3
exponent = 6**2

z = -45
abs_z = abs(z)

print(abs_z)

import math

my_float = 5.774843245

floor = math.floor(my_float)

ceiling = math.ceil(my_float)

print(floor)
print(ceiling)

round_float = round(my_float, 2)

print(round_float)

x = 5
x += 3

print(x)

my_string = "Hello"
my_string += " World"
print(my_string)

y = 4
y *= 2
print(y)