# -*- coding: utf-8 -*-
"""Strings & Numericals (repeat).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nHYgtIhCq0AiwOeFEoOJUmqbrdr57Vas
"""

print("This is the first sentence. \n This is another sentence.")

name = input("Enter your name: ")
name = name.lower()

age = input("Enter your age: ")

age = int(age)

current_year = 2023

year_turn_100 = current_year + (100 - age)

year_turn_100 = str(year_turn_100)

print("Hey " + name + " you will be 100 years old in " + year_turn_100)
print(f"Hey {name} you will be 100 years old in {year_turn_100}")



sentence = "Sunny days are the best. I am always in the best mood when it is sunny. If you ask me what the best weather is, I will say SUNNY!"

new_sentence = sentence.lower()

count_sunny = new_sentence.count("sunny")
print(count_sunny)

word = "Hello"
len_word = len(word)

print(len_word)

# Implicit casting
x = 10
y = 5.0
sum = x + y
sum = int(sum)
print(sum)

# Explicit casting
num = "42"
num_int = int(num)

product = 5*2
div = 20/2
mod = 9%3
exponent = 6**2

import math

my_float = 5.7885989

floor = math.floor(my_float)
ceiling = math.ceil(my_float)


age = -45
abs_age = abs(age)

# Rounding

my_float = 5.78948089989

round_float = round(my_float, 2)
print(round_float)

x = 5
x = x + 3

x += 3
print(x)

my_string = "Hello"
my_string += " World"
print(my_string)

y = 4
y *= 2