# -*- coding: utf-8 -*-
"""Control structures (repeat).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fzSYgH9nWkHp22hsaUjoL8LFJzssdLOf
"""

# Using the not operator

username = input("Enter your username: ")

if not username:
  print("Username name invalid. Please enter a valid username.")

else:
  print(f"Welcome {username}")

'''
Create a program that gets a user's age and determines if they are eligible
for a discount

'''

age = int(input("Enter your age (as a whole number): "))

is_member = input("Are you a member of our rewards program? yes or no").lower()

# Checking if user is a member and storing the appropriate boolean
if is_member == "yes":
  is_member = True

else:
  is_member = False

# Initialise the discount variable
discount = 0.0

if age >= 60:
  discount = 0.2

  if is_member:
    discount += 0.1

# Converting discount to a percentage and rounding
discount_per = discount * 100
rounded_discount = round(discount_per, 1)

print(f"Your discount percentage will be {rounded_discount}%")

# Eligibility for discounts
senior = discount > 0

# Recommending rewards program to eligible senior citizens
if senior and not is_member:
  print("Join our rewards program for additional discounts!")